// PHE-28 — Constellation data layer.
//
// The seven-pillar model, the deterministic node layout, and the read that feeds
// the Constellation tab. Content is generated by the engine (PHE-31 / see
// 06-engine-data.md) and served from `constellation_state` + `observations`.
//
// The canonical read is `apiFetch("/constellation")` (PHE-31). That endpoint is
// not live yet, so this module degrades gracefully: it falls back to a direct
// Supabase read of the same tables (owner-only via RLS, the shape the legacy
// `/constellation` page already uses) and, failing even that, to an empty state
// where all seven nodes still render with a count of 0. The tab never throws on
// a sparse or missing constellation.

import { apiFetch } from "@/lib/api-client";
import { supabaseBrowser as supabase } from "@/lib/supabase-browser";
import { STELLAR_DEFAULT } from "@/lib/stellar";

// ---------------------------------------------------------------------------
// Pillar model
// ---------------------------------------------------------------------------

export const ACTIVE_PILLARS = [
  "origin",
  "emergence",
  "self_creation",
  "convergence",
] as const;

export const LOCKED_PILLARS = ["becoming", "recognition", "transcendence"] as const;

export const ALL_PILLARS = [...ACTIVE_PILLARS, ...LOCKED_PILLARS] as const;

export type ActivePillar = (typeof ACTIVE_PILLARS)[number];
export type LockedPillar = (typeof LOCKED_PILLARS)[number];
export type Pillar = (typeof ALL_PILLARS)[number];

export function isLockedPillar(pillar: Pillar): pillar is LockedPillar {
  return (LOCKED_PILLARS as readonly string[]).includes(pillar);
}

/** Lowercase display label for a pillar (`self_creation` → `self creation`). */
export function pillarLabel(pillar: Pillar): string {
  return pillar.replace(/_/g, " ");
}

// ---------------------------------------------------------------------------
// Deterministic layout. Positions are normalized [0,1] within the canvas box so
// the constellation is visually stable across sessions and DPI. `z` is reserved
// for a future 3D layer — it is written and read (round-trips through the node
// model) but never consulted by the 2D draw, matching the persisted {x,y,z}
// contract in the spec.
// ---------------------------------------------------------------------------

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

export const NODE_LAYOUT: Record<Pillar, Vec3> = {
  origin: { x: 0.5, y: 0.85, z: 0.0 },
  emergence: { x: 0.22, y: 0.68, z: 0.1 },
  self_creation: { x: 0.16, y: 0.42, z: 0.2 },
  convergence: { x: 0.5, y: 0.48, z: 0.3 },
  becoming: { x: 0.82, y: 0.5, z: 0.4 },
  recognition: { x: 0.74, y: 0.24, z: 0.5 },
  transcendence: { x: 0.5, y: 0.12, z: 0.6 },
};

/** Faint, non-interactive edges between a precomputed pair set. */
export const EDGES: [Pillar, Pillar][] = [
  ["origin", "emergence"],
  ["origin", "convergence"],
  ["emergence", "self_creation"],
  ["emergence", "convergence"],
  ["self_creation", "convergence"],
  ["convergence", "becoming"],
  ["becoming", "recognition"],
  ["recognition", "transcendence"],
  ["convergence", "transcendence"],
];

// ---------------------------------------------------------------------------
// Normalized shapes consumed by the canvas + panel
// ---------------------------------------------------------------------------

export interface TimelineEntry {
  id: string;
  /** Voice-Standard prose. `null` when the server redacted a locked entry. */
  body: string | null;
  /** e.g. "cross-platform pattern / 6 months". */
  meta_label: string | null;
  surfaced_at: string;
  is_new: boolean;
}

export interface PillarDetail {
  pillar: Pillar;
  active: boolean;
  position: Vec3;
  score: number | null;
  synthesis: string | null;
  observation_count: number;
  has_new: boolean;
  /** Platform badges for the sources block (pro/gifted; omitted for free). */
  source_platforms: string[];
  /** Single source-insight paragraph shown under the platform badges. */
  source_insight: string | null;
  /** Dated entries, newest-first. */
  timeline: TimelineEntry[];
}

export interface ConstellationData {
  stellar_color: string;
  archetype: string | null;
  version: number | null;
  generated_at: string | null;
  /** IDENTITY PORTRAIT prose. */
  portrait: string | null;
  pillars: Record<Pillar, PillarDetail>;
}

// ---------------------------------------------------------------------------
// Fetch
// ---------------------------------------------------------------------------

function emptyPillar(pillar: Pillar): PillarDetail {
  return {
    pillar,
    active: !isLockedPillar(pillar),
    position: NODE_LAYOUT[pillar],
    score: null,
    synthesis: null,
    observation_count: 0,
    has_new: false,
    source_platforms: [],
    source_insight: null,
    timeline: [],
  };
}

function emptyState(stellarColor: string): ConstellationData {
  const pillars = {} as Record<Pillar, PillarDetail>;
  for (const pillar of ALL_PILLARS) pillars[pillar] = emptyPillar(pillar);
  return {
    stellar_color: stellarColor,
    archetype: null,
    version: null,
    generated_at: null,
    portrait: null,
    pillars,
  };
}

/** Best-effort stellar color for the current surface (payload > cache > default). */
function cachedStellarColor(): string {
  if (typeof window !== "undefined") {
    const stored = localStorage.getItem("phenyx_stellar_color");
    if (stored) return stored;
  }
  return STELLAR_DEFAULT;
}

/**
 * Normalize the PHE-31 endpoint payload into ConstellationData. Kept tolerant of
 * partial payloads so a half-populated constellation still renders every node.
 */
function normalizeEndpoint(raw: any, fallbackColor: string): ConstellationData {
  const base = emptyState(raw?.stellar_color ?? fallbackColor);
  base.archetype = raw?.archetype ?? null;
  base.version = raw?.version ?? null;
  base.generated_at = raw?.generated_at ?? null;
  base.portrait =
    typeof raw?.portrait === "string"
      ? raw.portrait
      : (raw?.portrait?.prose ?? null);

  const incoming: any[] = Array.isArray(raw?.pillars) ? raw.pillars : [];
  for (const p of incoming) {
    const key = p?.pillar as Pillar;
    if (!key || !base.pillars[key]) continue;
    const detail = base.pillars[key];
    detail.score = p.score ?? null;
    detail.synthesis = p.synthesis ?? null;
    detail.observation_count = p.observation_count ?? 0;
    detail.has_new = Boolean(p.has_new);
    detail.source_platforms = Array.isArray(p.source_platforms)
      ? p.source_platforms
      : [];
    detail.source_insight = p.source_insight ?? null;
    detail.timeline = Array.isArray(p.timeline)
      ? p.timeline.map((t: any) => ({
          id: String(t.id),
          body: t.body ?? null,
          meta_label: t.meta_label ?? null,
          surfaced_at: t.surfaced_at,
          is_new: Boolean(t.is_new),
        }))
      : [];
  }
  return base;
}

interface StateRow {
  archetype: string | null;
  version: number | null;
  generated_at: string | null;
  portrait: unknown;
  [key: string]: unknown;
}

interface ObservationRow {
  id: string;
  pillar: string;
  body: string;
  source_platforms: string[] | null;
  meta_label: string | null;
  is_new: boolean;
  surfaced_at: string;
}

/**
 * Fallback read straight from Supabase (owner-scoped via RLS) — the shape the
 * legacy `/constellation` page already relies on — so the tab shows real data
 * before the PHE-31 endpoint ships. Timeline gating is still applied in the
 * render layer, so free users never see more than the first two bodies here.
 */
async function readFromSupabase(fallbackColor: string): Promise<ConstellationData> {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return emptyState(fallbackColor);

  const [profileRes, stateRes, obsRes] = await Promise.all([
    supabase.from("user_profiles").select("stellar_color").eq("id", user.id).maybeSingle(),
    supabase.from("constellation_state").select("*").eq("user_id", user.id).maybeSingle(),
    supabase
      .from("observations")
      .select("id, pillar, body, source_platforms, meta_label, is_new, surfaced_at")
      .eq("user_id", user.id)
      .order("surfaced_at", { ascending: false }),
  ]);

  const stellarColor =
    (profileRes.data?.stellar_color as string | null) || fallbackColor;
  const data = emptyState(stellarColor);

  const state = stateRes.data as StateRow | null;
  if (state) {
    data.archetype = state.archetype ?? null;
    data.version = state.version ?? null;
    data.generated_at = state.generated_at ?? null;
    const portrait = state.portrait as { prose?: string } | string | null;
    data.portrait =
      typeof portrait === "string" ? portrait : (portrait?.prose ?? null);

    for (const pillar of ALL_PILLARS) {
      const score = state[`${pillar}_score`];
      const synthesis = state[`${pillar}_synthesis`];
      const detail = data.pillars[pillar];
      detail.score = typeof score === "number" ? score : null;
      detail.synthesis = typeof synthesis === "string" ? synthesis : null;
    }
  }

  const observations = (obsRes.data ?? []) as ObservationRow[];
  for (const obs of observations) {
    const detail = data.pillars[obs.pillar as Pillar];
    if (!detail) continue;
    detail.observation_count += 1;
    if (obs.is_new) detail.has_new = true;
    for (const platform of obs.source_platforms ?? []) {
      if (!detail.source_platforms.includes(platform)) {
        detail.source_platforms.push(platform);
      }
    }
    detail.timeline.push({
      id: obs.id,
      body: obs.body,
      meta_label: obs.meta_label,
      surfaced_at: obs.surfaced_at,
      is_new: obs.is_new,
    });
  }

  // The newest observation's meta label doubles as a source-insight line until
  // the endpoint serves the generated paragraph.
  for (const pillar of ALL_PILLARS) {
    const detail = data.pillars[pillar];
    if (!detail.source_insight && detail.timeline[0]?.meta_label) {
      detail.source_insight = detail.timeline[0].meta_label;
    }
  }

  return data;
}

/**
 * Read the current user's constellation. Tries the PHE-31 endpoint first, falls
 * back to a direct Supabase read, then to an empty (all-nodes, zero-count) state.
 * Never throws — a missing or sparse constellation still renders seven nodes.
 */
export async function fetchConstellation(): Promise<ConstellationData> {
  const fallbackColor = cachedStellarColor();

  try {
    const res = await apiFetch("/constellation");
    if (res.ok) {
      const raw = await res.json();
      return normalizeEndpoint(raw, fallbackColor);
    }
  } catch {
    // Endpoint not live / transport error — fall through to Supabase.
  }

  try {
    return await readFromSupabase(fallbackColor);
  } catch {
    return emptyState(fallbackColor);
  }
}

// ---------------------------------------------------------------------------
// Presentation helpers
// ---------------------------------------------------------------------------

/** Short relative age, e.g. "today", "3 days ago", "2 weeks ago". */
export function relativeTime(dateStr: string): string {
  const date = new Date(dateStr);
  if (Number.isNaN(date.getTime())) return "";
  const diffMs = Date.now() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays <= 0) return "today";
  if (diffDays === 1) return "yesterday";
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 14) return "1 week ago";
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`;
  if (diffDays < 60) return "1 month ago";
  return `${Math.floor(diffDays / 30)} months ago`;
}
