// PHE-28 — Constellation data layer.
//
// The seven-pillar model, the deterministic node layout, and the read that feeds
// the Constellation tab. Content is generated by the engine (PHE-31 / see
// 06-engine-data.md) and served from `constellation_state` + `observations`.
//
// The canonical read is `apiFetch("/constellation")` (PHE-31). That endpoint is
// not live yet, so this module degrades gracefully: it falls back to a direct
// Supabase read of the same tables (owner-only via RLS, the shape the legacy
// `/constellation` page already uses) and, failing even that, to an empty state
// where all seven nodes still render with a count of 0. The tab never throws on
// a sparse or missing constellation.

import { apiFetch } from "@/lib/api-client";
import { supabaseBrowser as supabase } from "@/lib/supabase-browser";
import { STELLAR_DEFAULT } from "@/lib/stellar";
import type { Evidence } from "@/components/phenyx/evidence-trace";

// ---------------------------------------------------------------------------
// Pillar model
// ---------------------------------------------------------------------------

export const ACTIVE_PILLARS = [
  "origin",
  "emergence",
  "self_creation",
  "convergence",
] as const;

export const LOCKED_PILLARS = ["becoming", "recognition", "transcendence"] as const;

export const ALL_PILLARS = [...ACTIVE_PILLARS, ...LOCKED_PILLARS] as const;

export type ActivePillar = (typeof ACTIVE_PILLARS)[number];
export type LockedPillar = (typeof LOCKED_PILLARS)[number];
export type Pillar = (typeof ALL_PILLARS)[number];

export function isLockedPillar(pillar: Pillar): pillar is LockedPillar {
  return (LOCKED_PILLARS as readonly string[]).includes(pillar);
}

/** Lowercase display label for a pillar (`self_creation` → `self creation`). */
export function pillarLabel(pillar: Pillar): string {
  return pillar.replace(/_/g, " ");
}

// ---------------------------------------------------------------------------
// Deterministic layout. Positions are normalized [0,1] within the canvas box so
// the constellation is visually stable across sessions and DPI. `z` is reserved
// for a future 3D layer — it is written and read (round-trips through the node
// model) but never consulted by the 2D draw, matching the persisted {x,y,z}
// contract in the spec.
// ---------------------------------------------------------------------------

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

export const NODE_LAYOUT: Record<Pillar, Vec3> = {
  origin: { x: 0.5, y: 0.85, z: 0.0 },
  emergence: { x: 0.22, y: 0.68, z: 0.1 },
  self_creation: { x: 0.16, y: 0.42, z: 0.2 },
  convergence: { x: 0.5, y: 0.48, z: 0.3 },
  becoming: { x: 0.82, y: 0.5, z: 0.4 },
  recognition: { x: 0.74, y: 0.24, z: 0.5 },
  transcendence: { x: 0.5, y: 0.12, z: 0.6 },
};

/** Faint, non-interactive edges between a precomputed pair set. */
export const EDGES: [Pillar, Pillar][] = [
  ["origin", "emergence"],
  ["origin", "convergence"],
  ["emergence", "self_creation"],
  ["emergence", "convergence"],
  ["self_creation", "convergence"],
  ["convergence", "becoming"],
  ["becoming", "recognition"],
  ["recognition", "transcendence"],
  ["convergence", "transcendence"],
];

// ---------------------------------------------------------------------------
// Normalized shapes consumed by the canvas + panel
// ---------------------------------------------------------------------------

export interface ClusterObservation {
  id: string;
  body: string | null;
  points?: string[] | null;
  sources?: string[] | null;
  span?: string | null;
  surfaced_at: string;
  is_new: boolean;
  /** Trace withheld (free). The sentence still ships. */
  locked?: boolean;
  evidence?: Evidence | null;
}

export interface Cluster {
  id: string;
  label: string;
  preview: string | null;
  observation_count: number;
  has_new: boolean;
  source_platforms: string[];
  observations: ClusterObservation[];
}

export interface PillarDetail {
  pillar: Pillar;
  active: boolean;
  position: Vec3;
  score: number | null;
  synthesis: string | null;
  observation_count: number;
  has_new: boolean;
  source_platforms: string[];
  source_insight: string | null;
  clusters: Cluster[];
}

export interface CanvasPoint {
  pillar: Pillar;
  x: number;
  y: number;
  z: number;
  active: boolean;
  has_new: boolean;
}

export interface RecordTimelineEra {
  start: number;
  width: number;
  name: string;
}

export interface RecordTimelineBreak {
  at: number;
  label: string;
}

export interface RecordTimelineCard {
  tag: string;
  line: string;
  evidence: Array<{ when: string; source: string; text: string }>;
}

export interface RecordTimeline {
  span: string[];
  note: string | null;
  eras: RecordTimelineEra[];
  breaks: RecordTimelineBreak[];
  return_line: string | null;
  card: RecordTimelineCard | null;
  empty: boolean;
}

export interface MovedPair {
  label: string;
  then: string;
  now: string;
}

export interface YearlyRecapEntry {
  when: string;
  text: string;
}

export interface ConstellationTenure {
  years: number;
  since: string | null;
}

export interface ConstellationData {
  stellar_color: string;
  archetype: string | null;
  version: number | null;
  generated_at: string | null;
  /** Portrait prose for "your story, right now". */
  portrait: string | null;
  points: CanvasPoint[];
  pillars: Record<Pillar, PillarDetail>;
  timeline: RecordTimeline;
  moved: MovedPair[];
  tenure: ConstellationTenure;
  yearly_recap: YearlyRecapEntry[] | null;
}

export const EMPTY_TIMELINE: RecordTimeline = {
  span: [],
  note: null,
  eras: [],
  breaks: [],
  return_line: null,
  card: null,
  empty: true,
};

// ---------------------------------------------------------------------------
// Fetch
// ---------------------------------------------------------------------------

function emptyPillar(pillar: Pillar): PillarDetail {
  return {
    pillar,
    active: !isLockedPillar(pillar),
    position: NODE_LAYOUT[pillar],
    score: null,
    synthesis: null,
    observation_count: 0,
    has_new: false,
    source_platforms: [],
    source_insight: null,
    clusters: [],
  };
}

function pointsFromPillars(pillars: Record<Pillar, PillarDetail>): CanvasPoint[] {
  return ALL_PILLARS.map((pillar) => {
    const layout = NODE_LAYOUT[pillar];
    const detail = pillars[pillar];
    return {
      pillar,
      x: layout.x,
      y: layout.y,
      z: layout.z,
      active: detail.active,
      has_new: detail.has_new,
    };
  });
}

function emptyState(stellarColor: string): ConstellationData {
  const pillars = {} as Record<Pillar, PillarDetail>;
  for (const pillar of ALL_PILLARS) pillars[pillar] = emptyPillar(pillar);
  return {
    stellar_color: stellarColor,
    archetype: null,
    version: null,
    generated_at: null,
    portrait: null,
    points: pointsFromPillars(pillars),
    pillars,
    timeline: { ...EMPTY_TIMELINE },
    moved: [],
    tenure: { years: 0, since: null },
    yearly_recap: null,
  };
}

/** Best-effort stellar color for the current surface (payload > cache > default). */
function cachedStellarColor(): string {
  if (typeof window !== "undefined") {
    const stored = localStorage.getItem("phenyx_stellar_color");
    if (stored) return stored;
  }
  return STELLAR_DEFAULT;
}

/**
 * Normalize the PHE-31 endpoint payload into ConstellationData. Kept tolerant of
 * partial payloads so a half-populated constellation still renders every node.
 */
function normalizeCluster(raw: any): Cluster | null {
  if (!raw || typeof raw !== "object") return null;
  const id = raw.id != null ? String(raw.id) : "";
  const label = typeof raw.label === "string" && raw.label.trim() ? raw.label.trim() : "core signals";
  const observations: ClusterObservation[] = Array.isArray(raw.observations)
    ? raw.observations.map((o: any) => ({
        id: String(o.id),
        body: o.body ?? null,
        points: Array.isArray(o.points) ? o.points : undefined,
        sources: Array.isArray(o.sources) ? o.sources : undefined,
        span: o.span ?? null,
        surfaced_at: o.surfaced_at ?? "",
        is_new: Boolean(o.is_new),
        locked: Boolean(o.locked),
        evidence: o.evidence ?? null,
      }))
    : [];
  return {
    id: id || label,
    label,
    preview: typeof raw.preview === "string" ? raw.preview : null,
    observation_count: raw.observation_count ?? observations.length,
    has_new: Boolean(raw.has_new),
    source_platforms: Array.isArray(raw.source_platforms) ? raw.source_platforms : [],
    observations,
  };
}

function normalizeTimeline(raw: any): RecordTimeline {
  if (!raw || typeof raw !== "object") return { ...EMPTY_TIMELINE };
  const eras: RecordTimelineEra[] = Array.isArray(raw.eras)
    ? raw.eras
        .map((e: any) => ({
          start: Number(e.start),
          width: Number(e.width),
          name: typeof e.name === "string" ? e.name : "",
        }))
        .filter((e: RecordTimelineEra) => e.name && Number.isFinite(e.start) && Number.isFinite(e.width))
    : [];
  const breaks: RecordTimelineBreak[] = Array.isArray(raw.breaks)
    ? raw.breaks
        .map((b: any) => ({
          at: Number(b.at),
          label: typeof b.label === "string" ? b.label : "",
        }))
        .filter((b: RecordTimelineBreak) => b.label && Number.isFinite(b.at))
    : [];
  const cardRaw = raw.card;
  const card: RecordTimelineCard | null =
    cardRaw && typeof cardRaw.tag === "string" && typeof cardRaw.line === "string"
      ? {
          tag: cardRaw.tag,
          line: cardRaw.line,
          evidence: Array.isArray(cardRaw.evidence)
            ? cardRaw.evidence
                .filter((ev: any) => ev && ev.when && ev.source && ev.text)
                .map((ev: any) => ({
                  when: String(ev.when),
                  source: String(ev.source),
                  text: String(ev.text),
                }))
            : [],
        }
      : null;
  const span = Array.isArray(raw.span)
    ? raw.span.filter((y: unknown): y is string => typeof y === "string")
    : [];
  return {
    span,
    note: typeof raw.note === "string" ? raw.note : null,
    eras,
    breaks,
    return_line: typeof raw.return_line === "string" ? raw.return_line : null,
    card,
    empty: raw.empty !== false && eras.length === 0,
  };
}

function normalizeEndpoint(raw: any, fallbackColor: string): ConstellationData {
  const base = emptyState(raw?.stellar_color ?? fallbackColor);
  base.archetype = raw?.archetype ?? null;
  base.version = raw?.version ?? null;
  base.generated_at = raw?.generated_at ?? null;
  base.portrait =
    typeof raw?.portrait === "string"
      ? raw.portrait
      : (raw?.portrait?.prose ?? null);

  const incoming: any[] = Array.isArray(raw?.pillars) ? raw.pillars : [];
  for (const p of incoming) {
    const key = p?.pillar as Pillar;
    if (!key || !base.pillars[key]) continue;
    const detail = base.pillars[key];
    detail.score = p.score ?? null;
    detail.synthesis = p.synthesis ?? null;
    detail.observation_count = p.observation_count ?? 0;
    detail.has_new = Boolean(p.has_new);
    detail.source_platforms = Array.isArray(p.source_platforms)
      ? p.source_platforms
      : [];
    detail.source_insight = p.source_insight ?? null;
    detail.clusters = Array.isArray(p.clusters)
      ? p.clusters.map(normalizeCluster).filter((c: Cluster | null): c is Cluster => c != null)
      : [];
    if (detail.clusters.length === 0 && Array.isArray(p.timeline) && p.timeline.length > 0) {
      detail.clusters = [
        {
          id: `${key}:core signals`,
          label: "core signals",
          preview: null,
          observation_count: p.timeline.length,
          has_new: detail.has_new,
          source_platforms: detail.source_platforms,
          observations: p.timeline.map((t: any) => ({
            id: String(t.id),
            body: t.body ?? null,
            surfaced_at: t.surfaced_at,
            is_new: Boolean(t.is_new),
            locked: t.body == null,
            evidence: t.evidence ?? null,
          })),
        },
      ];
    }
  }

  if (Array.isArray(raw?.points) && raw.points.length) {
    base.points = ALL_PILLARS.map((pillar) => {
      const found = raw.points.find((pt: any) => pt?.pillar === pillar);
      const layout = NODE_LAYOUT[pillar];
      const detail = base.pillars[pillar];
      return {
        pillar,
        x: typeof found?.x === "number" ? found.x : layout.x,
        y: typeof found?.y === "number" ? found.y : layout.y,
        z: typeof found?.z === "number" ? found.z : layout.z,
        active: found?.active ?? detail.active,
        has_new: found?.has_new ?? detail.has_new,
      };
    });
  } else {
    base.points = pointsFromPillars(base.pillars);
  }

  base.timeline = normalizeTimeline(raw?.timeline);
  base.moved = Array.isArray(raw?.moved)
    ? raw.moved
        .filter((m: any) => m && m.label && m.then && m.now)
        .map((m: any) => ({
          label: String(m.label),
          then: String(m.then),
          now: String(m.now),
        }))
    : [];
  base.tenure = {
    years: typeof raw?.tenure?.years === "number" ? raw.tenure.years : 0,
    since: typeof raw?.tenure?.since === "string" ? raw.tenure.since : null,
  };
  base.yearly_recap = Array.isArray(raw?.yearly_recap)
    ? raw.yearly_recap
        .filter((e: any) => e && e.when && e.text)
        .map((e: any) => ({ when: String(e.when), text: String(e.text) }))
    : null;

  return base;
}

interface StateRow {
  archetype: string | null;
  version: number | null;
  generated_at: string | null;
  portrait: unknown;
  [key: string]: unknown;
}

interface ObservationRow {
  id: string;
  pillar: string;
  body: string;
  source_platforms: string[] | null;
  meta_label: string | null;
  is_new: boolean;
  surfaced_at: string;
  area_id?: string | null;
}

interface AreaRow {
  id: string;
  pillar: string;
  label: string;
  ordinal: number;
}

const FALLBACK_CLUSTER_CAP = 2;

/**
 * Fallback read straight from Supabase (owner-scoped via RLS). Cluster entries
 * are capped at 2 so a missing endpoint never leaks the rest to free (fail closed).
 */
async function readFromSupabase(fallbackColor: string): Promise<ConstellationData> {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return emptyState(fallbackColor);

  const [profileRes, stateRes, obsRes, areasRes] = await Promise.all([
    supabase.from("user_profiles").select("stellar_color, created_at").eq("id", user.id).maybeSingle(),
    supabase.from("constellation_state").select("*").eq("user_id", user.id).maybeSingle(),
    supabase
      .from("observations")
      .select("id, pillar, body, source_platforms, meta_label, is_new, surfaced_at, area_id")
      .eq("user_id", user.id)
      .order("surfaced_at", { ascending: false }),
    supabase
      .from("areas")
      .select("id, pillar, label, ordinal")
      .eq("user_id", user.id)
      .order("ordinal", { ascending: true }),
  ]);

  const stellarColor =
    (profileRes.data?.stellar_color as string | null) || fallbackColor;
  const data = emptyState(stellarColor);
  const since = (profileRes.data?.created_at as string | null) ?? null;
  if (since) {
    const years = Math.max(0, (Date.now() - Date.parse(since)) / (365.25 * 24 * 60 * 60 * 1000));
    data.tenure = { years: Number.isFinite(years) ? years : 0, since };
  }

  const state = stateRes.data as StateRow | null;
  if (state) {
    data.archetype = state.archetype ?? null;
    data.version = state.version ?? null;
    data.generated_at = state.generated_at ?? null;
    const portrait = state.portrait as { prose?: string } | string | null;
    data.portrait =
      typeof portrait === "string" ? portrait : (portrait?.prose ?? null);

    for (const pillar of ALL_PILLARS) {
      const score = state[`${pillar}_score`];
      const synthesis = state[`${pillar}_synthesis`];
      const detail = data.pillars[pillar];
      detail.score = typeof score === "number" ? score : null;
      detail.synthesis = typeof synthesis === "string" ? synthesis : null;
    }
  }

  const observations = (obsRes.data ?? []) as ObservationRow[];
  const areas = (areasRes.error ? [] : (areasRes.data ?? [])) as AreaRow[];

  for (const pillar of ALL_PILLARS) {
    const detail = data.pillars[pillar];
    const pillarObs = observations.filter((o) => o.pillar === pillar);
    const pillarAreas = areas.filter((a) => a.pillar === pillar);
    const clusters: Cluster[] = [];

    const toObs = (rows: ObservationRow[]): ClusterObservation[] =>
      rows.slice(0, FALLBACK_CLUSTER_CAP).map((obs) => ({
        id: obs.id,
        body: obs.body,
        sources: obs.source_platforms ?? undefined,
        surfaced_at: obs.surfaced_at,
        is_new: obs.is_new,
        locked: true,
        evidence: null,
      }));

    for (const area of pillarAreas) {
      const rows = pillarObs.filter((o) => o.area_id === area.id);
      if (!rows.length) continue;
      const served = toObs(rows);
      clusters.push({
        id: area.id,
        label: area.label || "core signals",
        preview: served[0]?.body ?? null,
        observation_count: served.length,
        has_new: rows.some((r) => r.is_new),
        source_platforms: [...new Set(rows.flatMap((r) => r.source_platforms ?? []))],
        observations: served,
      });
    }

    const core = pillarObs.filter((o) => !o.area_id);
    if (core.length) {
      const served = toObs(core);
      clusters.push({
        id: `${pillar}:core signals`,
        label: "core signals",
        preview: served[0]?.body ?? null,
        observation_count: served.length,
        has_new: core.some((r) => r.is_new),
        source_platforms: [...new Set(core.flatMap((r) => r.source_platforms ?? []))],
        observations: served,
      });
    }

    detail.clusters = clusters;
    detail.observation_count = clusters.reduce((n, c) => n + c.observation_count, 0);
    detail.has_new = clusters.some((c) => c.has_new);
    detail.source_platforms = [...new Set(clusters.flatMap((c) => c.source_platforms))];
    if (clusters[0]?.preview) detail.source_insight = clusters[0].preview;
  }

  data.points = pointsFromPillars(data.pillars);
  return data;
}

/**
 * Read the current user's constellation. Tries the PHE-31 endpoint first, falls
 * back to a direct Supabase read, then to an empty (all-nodes, zero-count) state.
 * Never throws — a missing or sparse constellation still renders seven nodes.
 */
export async function fetchConstellation(): Promise<ConstellationData> {
  const fallbackColor = cachedStellarColor();

  try {
    const res = await apiFetch("/constellation");
    if (res.ok) {
      const raw = await res.json();
      return normalizeEndpoint(raw, fallbackColor);
    }
  } catch {
    // Endpoint not live / transport error — fall through to Supabase.
  }

  try {
    return await readFromSupabase(fallbackColor);
  } catch {
    return emptyState(fallbackColor);
  }
}

// ---------------------------------------------------------------------------
// Presentation helpers
// ---------------------------------------------------------------------------

/** Short relative age, e.g. "today", "3 days ago", "2 weeks ago". */
export function relativeTime(dateStr: string): string {
  const date = new Date(dateStr);
  if (Number.isNaN(date.getTime())) return "";
  const diffMs = Date.now() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays <= 0) return "today";
  if (diffDays === 1) return "yesterday";
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 14) return "1 week ago";
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`;
  if (diffDays < 60) return "1 month ago";
  return `${Math.floor(diffDays / 30)} months ago`;
}
